FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y && \
    apt-get -y install build-essential python-setuptools python2.7 python2.7-dev libssl-dev git tox python-pip vim && \
    pip install elastalert requests -i https://mirrors.aliyun.com/pypi/simple/
